# Generated by Django 3.0.7 on 2020-07-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songpost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('album_logo', models.ImageField(upload_to='images')),
                ('file', models.FileField(upload_to='musics')),
            ],
        ),
    ]
