# Generated by Django 3.0.7 on 2020-07-11 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songuserpost',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('song_title', models.CharField(max_length=250)),
                ('artist', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=100)),
                ('slug', models.CharField(max_length=100)),
                ('album_logo', models.ImageField(upload_to='images')),
                ('music', models.FileField(upload_to='musics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
