# Generated by Django 3.0.7 on 2020-07-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_songuserpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='songuserpost',
            name='desc',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='songuserpost',
            name='tag',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='songuserpost',
            name='album_logo',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='songuserpost',
            name='album_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='songuserpost',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='songuserpost',
            name='music',
            field=models.FileField(default='', upload_to='musics'),
        ),
    ]
