# Generated by Django 3.0.7 on 2020-07-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20200711_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songuserpost',
            name='user',
        ),
        migrations.AlterField(
            model_name='songuserpost',
            name='music',
            field=models.FileField(upload_to='musics'),
        ),
    ]
