# Generated by Django 3.0.7 on 2020-07-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_auto_20200711_1132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Songuserpost',
        ),
        migrations.AddField(
            model_name='songpost',
            name='desc',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='songpost',
            name='tags',
            field=models.CharField(default='', max_length=500),
        ),
    ]
