# Generated by Django 3.0.7 on 2020-06-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200626_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
