# Generated by Django 3.0.7 on 2020-07-08 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogupload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogupload',
            old_name='views',
            new_name='bviews',
        ),
    ]
