# Generated by Django 3.0.7 on 2020-07-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200709_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogupload',
            old_name='slug',
            new_name='bslug',
        ),
    ]
