# Generated by Django 3.0.7 on 2020-07-09 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200709_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogupload',
            old_name='bauthor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='blogupload',
            old_name='bcontent',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='blogupload',
            old_name='bimages',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='blogupload',
            old_name='bslug',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='blogupload',
            old_name='btitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='blogupload',
            old_name='bviews',
            new_name='views',
        ),
    ]
