# Generated by Django 3.0.7 on 2020-07-11 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200710_1825'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogupload',
        ),
    ]
