# Generated by Django 3.0.7 on 2020-07-16 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
