# Generated by Django 3.0.7 on 2020-08-02 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200802_2349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='uploader',
        ),
    ]
